polling_station/urls.py
from django.contrib import admin
from django.urls import path, include
from student import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

app_name = 'main'

urlpatterns = [
    path('votting/', include('votting.urls', namespace='votting')),
    path('candidate/', include('candidate.urls', namespace='candidate')),
    path('student/', include('student.urls', namespace='student')),
    path('', views.start_page, name='start'),
    path('homepage/', views.home_page, name='homepage'),
    path('student/login/', views.login_page, name='login'),
    path('student/enroll/', views.enroll_page, name='enroll'),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path, re_path
from . import views

app_name = 'student'

urlpatterns = [
    # re_path(r'^$', views.student_hp, name='homepage'),
    path('<str:slug>/login', views.login_page),
    path('login/', views.login_page, name='login'),
    path('start-enroll/', views.enroll_page, name='enroll'),
    path('profile/', views.profile, name='profile'),
    path('feedback/', views.feedback, name='feedback'),
    path('User-comment/', views.comment, name='comment'),
    path('posts/', views.posts, name='posts'),
    path('posts/let-me-create-a-post/', views.make_post, name='make_post'),
    path('posts/add-comment-to-current-post/<str:slug>', views.post_comment, name='post_comment'),
    path('posts/like-current-post/<str:slug>', views.like_post, name='like'),
    path('create-a-user-account/', views.create_user, name='enroll1'),
    path('enrolled-thanks/', views.enrolled, name='enrolled'),
    path('log-out-current-user/', views.logout_user, name='logout'),
    path('privacy-policies-and-agreement-terms/', views.privacy, name='privacy'),

]

votting/urls.py
from django.urls import path, re_path
from . import views

app_name = 'votting'
urlpatterns = [
    re_path(r'^$', views.votting_hp, name='homepage'),
    path('nominated-candidates/', views.nominated, name='nominated'),
    path('non-nominated-candidates/', views.nonNominated, name='non-nominated'),
    path('vote-your-favourites-candidates/', views.vote, name='vote'),
]

votting/models.py
from django.db import models

# Create your models here.

class Vote(models.Model):
    colleges = [('CEDAT', 'College Of Engineering Design Art ANd Technology'),
                ('COBAMS', 'Economics')
                ]
    departments = []
    programs = []
    year = [('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')]
    sexes = [('m', 'Male'), ('f', 'female'), ('u', 'undefined')]

    college = models.CharField(max_length=100, choices=colleges, help_text='From the dropdown menu select your college')
    department = models.CharField(max_length=100, help_text='Choose your department')
    program = models.CharField(max_length=50, help_text='What is your Program')
    year_of_study = models.CharField(max_length=4, choices=year, help_text='Select your your of study')
    full_name = models.CharField(max_length=100, help_text='Enter Your full official name')
    reg_no = models.CharField(max_length=20, primary_key=True, help_text='Enter your Registration number')
    student_no = models.CharField(max_length=20, default='', help_text='Your student number')
    date_of_birth = models.DateField(blank=True, null=True, help_text='Enter your birthday')
    email = models.EmailField(default='', help_text='The email will only be used for official purposes')
    photo = models.ImageField(blank=True, default='default.jpg', help_text='This will be your profile picture')
    sex = models.CharField(max_length=10, choices=sexes, help_text='Sex', default='')
    post = models.CharField(max_length=100, help_text='post of leadership')
    vote = models.BooleanField(help_text='student vote', default=False)
    nominated = models.BooleanField(help_text='Nominated Candidate', default=False)

    def __str__(self):
        return self.full_name

votting/views.py
from django.shortcuts import render
from student.models import Profile
from . import models
from django.http import HttpResponse

# Create your views here.

def votting_hp(request):
    details = Profile.objects.get(student_no=request.user)
    votes = models.Vote.objects.all()
    nominated = []
    non_nominated = []
    for i in votes:
        if i.nominated:
            nominated.append(i)
        else:
            non_nominated.append(i)
    context = {
        'l_nominated':len(nominated), 'l_nonNominated':len(non_nominated),
        'nominated':nominated, 'non_nominated':non_nominated, 'contestants':votes, 'details':details,
        'total_number':len(votes)
    }
    return render(request, 'votting/intro.html', context)

def nominated(request):
    details = Profile.objects.get(student_no=request.user)
    votes = models.Vote.objects.all()
    nominated = []
    for i in votes:
        if i.nominated:
            nominated.append(i)
    context = {
        'l_nominated': len(nominated),
        'nominateds': nominated, 'contestants': votes, 'details': details
    }
    return render(request, 'votting/nominated.html', context)

def nonNominated(request):
    details = Profile.objects.get(student_no=request.user)
    votes = models.Vote.objects.all()
    non_nominated = []
    for i in votes:
        if not i.nominated:
            non_nominated.append(i)
    context = {
        'l_nonNominated': len(non_nominated),
        'non_nominateds': non_nominated, 'contestants': votes, 'details': details
    }
    return render(request, 'votting/nonNominated.html', context)

def vote(request):
    details = Profile.objects.get(student_no=request.user)
    votes = models.Vote.objects.all()
    nominated = []
    non_nominated = []
    for i in votes:
        if i.nominated:
            nominated.append(i)
        else:
            non_nominated.append(i)
    context = {
        'l_nominated': len(nominated), 'l_nonNominated': len(non_nominated),
        'nominated': nominated, 'non_nominated': non_nominated, 'contestants': votes, 'details': details,
        'total_number': len(votes)
    }
    return render(request, 'votting/vote.html', context)

votting/templates/votting/base.html
{% extends 'polling_station/base_template.html' %}

{% block side-nav %}
    <ul class="vertical-list">
        <h4>What do you wanna see?</h4>
        <li> <a href="{% url 'votting:nominated' %}" class="dd-a"><b>Nominated Candidates</b></a> </li>
        <li> <a href="{% url 'votting:non-nominated' %}" class="dd-a"><b>Non-nominated Candidates</b></a> </li>
        <li> <a href="{% url 'votting:vote' %}" class="dd-a"><b>vote</b></a> </li>
      </ul>
{% endblock %}

votting/templates/votting/intro.html
{% extends 'votting/base.html'%}

{% block content %}

<h1>This is the section that concerns votes</h1>
<p>Brief Statistics of Candidates this academic year</p>
<table>
    <tr>
        <th colspan="5" onclick="voteDetails('vote-details')">No of Colleges</th>
        <td onclick="voteDetails('vote-details')">09</td>
        <div class="vote-details" id="vote-details">
            <button type="button" onclick="voteDetails('vote-details')" style="display: block; background-color: red; color: white">
                Exit</button>
                <button type="button" style="bottom: 0; padding: 0 1px; width: auto; height: 10px; font-size: smaller;">+</button>
                CEDAT
            <div class="brief-detail-about-vote" id="college-cedat">
                <h5><b>CEDAT:</b></h5>
                <p>CEDAT:- In full this stands for College of Engineering, Design, Art And technology. <br />
                This college have severall departments which includes;-
                    <ul style="list-style: circle; text-align: center;">
                <li>Department of Elecrical and Computer Engineering</li>
                <li>Department of Mechanical Engineering</li>
                <li>Department of Civil Engineering</li>
            </ul>
                </p>
            </div>
            <div onclick="collegeDetails('college-cobams')">COBAMS</div>
             <div class="brief-detail-about-vote" id="college-cobams">
                <h5><b >CEDAT:</b></h5>
                <p>CEDAT:- In full this stands for College of Engineering, Design, Art And technology. <br />
                This college have severall departments which includes;-
                    <ul style="list-style: circle; text-align: center;">
                <li>Department of Elecrical and Computer Engineering</li>
                <li>Department of Mechanicla Engineering</li>
                <li>Department of Civil Engineering</li>
            </ul>
                </p>
            </div>
            <p>colleges</p>
            <p>colleges</p>
        </div>

    </tr>
    <tr>
        <th colspan="5" onclick="voteDetails('vote-detail1')">Total number of posts</th>
        <td onclick="voteDetails('vote-detail1')">0</td>
        <div class="vote-details" id="vote-detail1">
            <button type="button" onclick="voteDetails('vote-detail1')" style="display: block; background-color: red; color: white">
                Exit</button>
            <p>colleges</p>
            <p>colleges</p>
            <p>colleges</p>
            <p>colleges</p>
        </div>
    </tr>
    <tr>
        <th colspan="5" onclick="voteDetails('vote-detail2')">Number of Contestants</th>
        <td onclick="voteDetails('vote-detail2')">{{ total_number }}</td>
        <div class="vote-details" id="vote-detail2">
            <button type="button" onclick="voteDetails('vote-detail2')" style="display: block; background-color: red; color: white">
                Exit</button>
            <p>colleges</p>
            <p>colleges</p>
            <p>colleges</p>
            <p>colleges</p>
        </div>
    </tr>
    <tr>
        <th colspan="5" onclick="voteDetails('vote-detail3')">Currently Nominated by Students</th>
        <td onclick="voteDetails('vote-detail3')">{{ l_nominated }}</td>
        <div class="vote-details" id="vote-detail3">
            <button type="button" onclick="voteDetails('vote-detail3')" style="display: block; background-color: red; color: white">
                Exit</button>
            <p>colleges</p>
            <p>colleges</p>
            <p>colleges</p>
            <p>colleges</p>
        </div>
    </tr>
    <tr>
        <th colspan="5" onclick="voteDetails('vote-detail4')">Yet to be nominated by Students</th>
        <td onclick="voteDetails('vote-detail4')">{{ l_nonNominated }}</td>
        <div class="vote-details" id="vote-detail4">
            <button type="button" name="vote-detail4" onclick="voteDetails(this.name)" style="display: block; background-color: red; color: white">
                Exit</button>
            <p>colleges</p>
            <p>colleges</p>
            <p>colleges</p>
            <p>colleges</p>
        </div>
    </tr>
</table>
{% endblock %}

votting/templates/votting/nominated.html
{% extends 'votting/base.html' %}

{% block content%}
<h3>We Will Show You Students Nominated By The Student Body</h3>
{% if l_nominated == 0 %}
    <h2 style="color: red">
        We are sorry, as for now we have no data to display you for your current query.
    </h2>
{% else %}
    {% for nominated in nominateds %}
        <p>We got you</p>
    {% endfor %}
{% endif %}

{% endblock %}

votting/templates/votting/nonNominated.html
{% extends 'votting/base.html' %}

{% block content%}
<h3>We Will Show You Students Nominated By The Student Body</h3>
{% if l_nonNominated == 0 %}
    <h2 style="color: red">
        We are sorry, as for now we have no data to display you for your current query.
    </h2>
{% else %}
    {% for non_nominated in non_nominateds %}
        <p>We got you</p>
    {% endfor %}
{% endif %}

{% endblock %}

votting/templates/votting/vote.html
{% extends 'votting/base.html' %}

{% block content%}
<h3>We Will Show You Students Nominated By The Student Body</h3>
{% if l_nominated == 0 %}
    <h2 style="color: red">
        We are sorry, as for now we have no data to display you for your current query.
    </h2>
{% else %}
    {% for nominated in nominateds %}
        <p>We got you</p>
    {% endfor %}
{% endif %}

{% endblock %}