polling_station/urls.py
from django.contrib import admin
from django.urls import path, include
from student import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

app_name = 'main'

urlpatterns = [
    path('votting/', include('votting.urls', namespace='votting')),
    path('candidate/', include('candidate.urls', namespace='candidate')),
    path('student/', include('student.urls', namespace='student')),
    path('', views.start_page, name='start'),
    path('homepage/', views.home_page, name='homepage'),
    path('student/login/', views.login_page, name='login'),
    path('student/enroll/', views.enroll_page, name='enroll'),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path, re_path
from . import views

app_name = 'student'

urlpatterns = [
    # re_path(r'^$', views.student_hp, name='homepage'),
    path('<str:slug>/login', views.login_page),
    path('login/', views.login_page, name='login'),
    path('start-enroll/', views.enroll_page, name='enroll'),
    path('profile/', views.profile, name='profile'),
    path('feedback/', views.feedback, name='feedback'),
    path('User-comment/', views.comment, name='comment'),
    path('posts/', views.posts, name='posts'),
    path('posts/let-me-create-a-post/', views.make_post, name='make_post'),
    path('posts/add-comment-to-current-post/<str:slug>', views.post_comment, name='post_comment'),
    path('posts/like-current-post/<str:slug>', views.like_post, name='like'),
    path('create-a-user-account/', views.create_user, name='enroll1'),
    path('enrolled-thanks/', views.enrolled, name='enrolled'),
    path('log-out-current-user/', views.logout_user, name='logout'),
    path('privacy-policies-and-agreement-terms/', views.privacy, name='privacy'),

]

templates/polling_station/base_template.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <link rel="stylesheet" href="https://cdngs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
      {%load static from staticfiles%}
      <link rel="stylesheet" href="{% static 'styles.css'%}">
    <script type="text/javascript" src="{% static 'script.js' %}"></script>

    <script type="text/javascript">



    </script>

    <title>Polling Station</title>
  </head>
  <body>
  <div class="grid-container">
    <div class="grid-container1">
      <div class="topnav">
          <a href="{% url 'homepage' %}" class="active"> Homepage </a>
          <a href="{% url 'candidate:homepage' %}" class="active"> candidates </a>
          <a href="{% url 'votting:homepage' %}" class="active"> vote </a>
          <a href="{% url 'student:posts' %}" class="active"> posts </a>
        <div class="action-button">
          <button class="three-bar1" onclick="actionButton()">
          <span ><b>---</b></span>
          <br />
          <span ><b>---</b></span>
          <br />
          <span ><b>---</b></span>
          </button>

        </div>
      </div>
    </div>
    <div class="content">
      <div class="side-nav">
      {% block side-nav %}

      {% endblock %}

    </div>
      <div class="side-detail">
          <div class="action-button-content" id="action-button" >
              <span>
                  <img id="action-image" src="{{ details.photo.url }}" alt="profile">
                  <p style="float: inside; display: block">Logged In As</p>
              </span>
              <b><p style="display: block; text-decoration: none; text-align: center">{{details.full_name}}</p></b>
              <a href="{% url 'student:feedback' %}" color="red"><strong>Feedback Forum</strong></a>
              <a href="#" color="red"><strong>Settings</strong></a>
              <a href="{% url 'student:profile' %}" color="red"><strong>Account</strong></a>
              <a href="{% url 'student:logout' %}" color="red"><strong>Log Out</strong></a>
          </div>
      <img src="/media/muk-logo.jpg" class="muk-logo" alt="Makerere" />
      {%block content%}


      {%endblock%}

       <hr />
    <div>
      <form action="{% url 'student:comment' %}" method="POST" class="comment-class">
        {% csrf_token %}
        <p><b>We will love your feedback, so please consider filling the below form</b></p>
        <textarea id="comment-input" cols="40" rows="3" name="comment">Please Enter Your comment here...</textarea>
         <button type="submit" onclick="alertNotice()">Submit Comment</button>
    </form>
    </div>
    <hr />
    <footer>
      <p><b style="display: inline-block;"> <a href="{% url 'student:privacy' %}" style="color: red; text-align: center;"><u>Privacy</u></a> And
          <a href="{% url 'student:privacy' %}" style="color: red; text-align: center;"><u>Agreement</u></a> Policies.
          <a href="{% url 'student:privacy' %}" style="color: red; text-align: center;"><u>Read</u></a></b></p>
      <p>This Program is developed purposely for the intended use by
          <a href="#" style="color: red; text-align: center;"><u>Makerere university</u></a> for other uses and parties
      please seek the developers consent</p>
      <strong>Developed by <b><a href="http://tipan-coders.simplesite.com" target="_blank" style="color: red; text-align: center;">
          <u>STA-Tipan-Coders</u></a></b></strong>
        <p style="color: #CC3434">Note: Clicking the above link will direct you to the Developer's Website on a new Window.</p>
    </footer>

    </div>
    </div>

  </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

  </body>
</html>

templates/polling_station/intro.html
{% extends 'student/base.html'%}

{% block content %}
<h1> Makerere University Online Polling Station </h1>
<p> </p>
<h2> Welcome to our online resource </h2>
{% endblock %}

templates/polling_station/start_page.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description"
    content="Online Polling Station For Makerere University, Uganda" />
    <meta name="keywords"
    content="Polling, polling, Polling Station, polling station, Polling-Station, polling-station,
     Makerere Polling Station, makerere polling station, muk polling station, muk poll, STA Poll, sta poll, STA poll" />
    <meta name="robots"
    content="nofollow" />
    <meta http-equiv="author"
          content="Stephen Tipa Augustine" />
    <meta http-equiv="pragma"
     content="no-cache" />

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {%load static from staticfiles%}
      <link rel="stylesheet" href="{% static 'styles.css'%}">
    <title>Polling Station</title>
  </head>
  <body>
     <h1> Makerere University Online Polling Station </h1>
     <h2> Welcome to our online resource </h2>
     <p>If you already have an account or you have enrolled into the system then simply login by following the <b>Login</b> link</p>
    <div class="div-a">
        <a href="{% url 'login' %}" class="lonely-a">Login To Your Account</a>
    </div>
    <p>If you don't have an account or you have not enrolled yet into the system then simply <strong>Enroll</strong> by following
        the <b>Enroll</b> link</p>
    <div class="div-a">
        <a href="{% url 'enroll' %}" class="lonely-a">Enroll Into The System</a>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/polling_station/terms.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {%load static from staticfiles%}
      <link rel="stylesheet" href="{% static 'styles.css'%}">
    <title>Polling Station</title>
  </head>
  <body>
     <h1>Privacy Policies, And Terms And Conditions</h1>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>