polling_station/urls.py
from django.contrib import admin
from django.urls import path, include
from student import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

app_name = 'main'

urlpatterns = [
    path('votting/', include('votting.urls', namespace='votting')),
    path('candidate/', include('candidate.urls', namespace='candidate')),
    path('student/', include('student.urls', namespace='student')),
    path('', views.start_page, name='start'),
    path('homepage/', views.home_page, name='homepage'),
    path('student/login/', views.login_page, name='login'),
    path('student/enroll/', views.enroll_page, name='enroll'),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path, re_path
from . import views

app_name = 'student'

urlpatterns = [
    # re_path(r'^$', views.student_hp, name='homepage'),
    path('<str:slug>/login', views.login_page),
    path('login/', views.login_page, name='login'),
    path('start-enroll/', views.enroll_page, name='enroll'),
    path('profile/', views.profile, name='profile'),
    path('feedback/', views.feedback, name='feedback'),
    path('User-comment/', views.comment, name='comment'),
    path('posts/', views.posts, name='posts'),
    path('posts/let-me-create-a-post/', views.make_post, name='make_post'),
    path('posts/add-comment-to-current-post/<str:slug>', views.post_comment, name='post_comment'),
    path('posts/like-current-post/<str:slug>', views.like_post, name='like'),
    path('create-a-user-account/', views.create_user, name='enroll1'),
    path('enrolled-thanks/', views.enrolled, name='enrolled'),
    path('log-out-current-user/', views.logout_user, name='logout'),
    path('privacy-policies-and-agreement-terms/', views.privacy, name='privacy'),

]

student/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# Create your models here.

class Login(models.Model):
    reg_no = models.CharField(max_length=20)
    student_no = models.CharField(max_length=20)
    password = models.CharField(max_length=50)
    def __str__(self):
        return self.student_no
class Profile(models.Model):
    colleges = [('CEDAT', 'College Of Engineering Design Art ANd Technology'),
                ('COBAMS', 'Economics')
                ]
    departments = []
    programs = []
    year = [('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')]

    college = models.CharField(max_length=100, choices=colleges, help_text='From the dropdown menu select your college')
    department = models.CharField(max_length=100, help_text='Choose your department')
    program = models.CharField(max_length=50, help_text='What is your Program')
    year_of_study = models.CharField(max_length=4, choices=year, help_text='Select your your of study')
    full_name = models.CharField(max_length=100, help_text='Enter Your full official name')
    reg_no = models.CharField(max_length=20, primary_key=True, help_text='Enter your Registration number')
    student_no = models.CharField(max_length=20, default='', help_text='Your student number')
    date_of_birth = models.DateField(blank=True, null=True, help_text='Enter your birthday')
    email = models.EmailField(default='', help_text='The email will only be used for official purposes')
    photo = models.ImageField(blank=True, default='default.jpg', help_text='This will be your profile picture')
    phone = models.CharField(max_length=10, default="")
    mobile = models.CharField(max_length=10, default="")
    def __str__(self):
        return self.full_name

class Comment(models.Model):
    user = models.ForeignKey(User, default=None, on_delete=models.PROTECT)
    comment = models.TextField()
    photo = models.ImageField(help_text='An Image', blank=True)
    time = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.comment[:100]+'...'

class Posts(models.Model):
    key = models.CharField(max_length=100, help_text='pk1', default='', primary_key=True)
    keyComment = models.CharField(max_length=100, help_text='pk2', default='')
    photo = models.ImageField(blank=True, default='default.jpg', help_text='Your Image')
    userPhoto = models.ImageField(blank=True, default='default.jpg', help_text='Your Image')
    post = models.TextField(help_text='Your post')
    user = models.ForeignKey(User, default=None, on_delete=models.PROTECT)
    time = models.DateTimeField(auto_now_add=True)
    likes = models.IntegerField(help_text='Likes', default=0)
    comments = models.IntegerField(help_text='comments', default=0)
    def __str__(self):
        return self.post[:100]+'...'

class PostComments(models.Model):
    post = models.TextField(help_text='Your', default='')
    photo = models.ImageField(blank=True, default='default.jpg', help_text='Your Image')
    user = models.ForeignKey(User, default=None, on_delete=models.PROTECT)
    time = models.DateTimeField(auto_now_add=True)
    comment = models.TextField(help_text='comments', default='')
    def __str__(self):
        return self.comment[:100]+'...'

class PostLikes(models.Model):
    post = models.TextField(help_text='Your', default='')
    photo = models.ImageField(blank=True, default='default.jpg', help_text='Your Image')
    user = models.ForeignKey(User, default=None, on_delete=models.PROTECT)
    time = models.DateTimeField(auto_now_add=True)
    likes = models.BooleanField(help_text='Likess', default=False)

    def __str__(self):
        return self.post[:100] + '...'

student/forms.py
from django import forms
from . import models

import datetime
class StudentDetails(forms.ModelForm):
    class Meta:
        model = models.Profile
        fields = "__all__"
        labels = {
            'college':'Your College', 'department':'Your department', 'program':'Your Program',
            'year_of_study':'Year of study', 'full_name':'Full Name', 'reg_no':'Registration number',
            'date_of_birth':'Date of Birth', 'email':'Your Email', 'photo':'Select a photo',
            'mobile':'Mobile number', 'phone':'Phone number'
        }
        widgets = {
            'date_of_birth': forms.SelectDateWidget(years=[i for i in range(datetime.date.today().year, 1900, -1)])
        }
        help_texts={
            'photo': 'As your profile picture'
        }

class Post( forms.ModelForm ):
    class Meta:
        model = models.Posts
        fields = ['post', 'photo']

class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ['comment']
class PostComment(forms.ModelForm):
    class Meta:
        model = models.PostComments
        fields = ['comment']

class Like(forms.ModelForm):
    class Meta:
        model = models.Posts
        fields = ['likes']
class Comment(forms.ModelForm):
    class Meta:
        model = models.Posts
        fields = ['comments']

student/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from . import forms
from . import models
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core import serializers
import json

# Create your views here.
@login_required(login_url='start')
def posts(request):
    l = models.Posts.objects.order_by('time')
    comments = models.PostComments.objects.order_by('time')
    likes = models.PostLikes.objects.order_by('time')
    details = models.Profile.objects.get(student_no=request.user)
    o = len(likes)
    n = len(l)
    m = len(comments)
    post = []
    comment = []
    like = []
    for i in range(n-1, -1, -1):
        post.append(l[i])
    for i in range(m-1, -1, -1):
        comment.append(comments[i])
    for i in range(o-1, -1, -1):
        like.append(l[i])
    return render(request, 'student/posts.html', {'details':details, 'posts':post, 'comments':comment, 'likes':like})
def privacy(request):
    return render(request, 'polling_station/terms.html')
@login_required(login_url='start')
def feedback(request):
    comments = models.Comment.objects.all()
    details = models.Profile.objects.get(student_no=request.user)
    return render(request, 'student/feedback.html', {'comments':comments, 'details':details})
@login_required(login_url='start')
def profile(request):
    details = models.Profile.objects.get(student_no=request.user)
    return render(request, 'student/profile.html', {'details':details})
def start_page(request):
    return render(request, 'polling_station/start_page.html')
@login_required(login_url='start')
def home_page(request):
    details = models.Profile.objects.get(student_no=request.user)
    return render(request, 'polling_station/intro.html', {'details':details})
def enrolled(request):
    return render(request, 'student/enrolled.html')
def comment(request):
    form = forms.CommentForm(request.POST)
    if request.method == 'POST':
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
    return redirect(request.META.get('HTTP_REFERER'))

def login_page(request):
    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('homepage')
    else:
        form = AuthenticationForm()
    return render(request, "student/login.html", {'form':form})
def create_user(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            user = post.save()
            login(request, user)
            return redirect('student:enrolled')
    else:
        form = UserCreationForm()
    return render(request, 'student/enroll1.html', {'user_form':form})

def enroll_page(request):
    if request.method == 'POST':
        form = forms.StudentDetails(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('student:enroll1')
    else:
        form = forms.StudentDetails()
    return render(request, "student/enroll.html", {'form':form})

def logout_user(request):
    logout(request)
    messages.info(request, "Logged out successfully")
    return render(request, 'student/logout.html')

def make_post(request):
    if request.method == 'POST':
        print(request.POST)
        print("The image file")
        print(request.FILES)
        form = forms.Post(request.POST, request.FILES)
        details = models.Profile.objects.get(student_no=request.user)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.userPhoto = details.photo
            new = post.post[:20].split(' ')
            new1 = str(post.time).split(' ')
            new1 = '_'.join(new1) + '_'
            new = '_'.join(new) + '_'
            for i in "./,\n":
                new = new.replace(i, '')
            for i in ":;./,\n":
                new1 = new1.replace(i, '')
            post.key = new + new1 + str(request.user)
            post.keyComment = post.key + '_1'
            post.save()
            return redirect(request.META.get('HTTP_REFERER'))
    else:
        form = forms.Post()
    return redirect(request.META.get('HTTP_REFERER'), {'post_form':form})
def post_comment(request, slug):
    if request.method == 'POST':
        form = forms.PostComment(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.post = str(slug)
            post.save()
            comment = models.Posts.objects.all()
            for i in comment:
                if i.post == str(slug):
                    i.comments +=1
                    i.save()
    return redirect(request.META.get('HTTP_REFERER'))

def like_post(request, slug):
    fuck = models.Posts.objects.all()
    obj = models.PostLikes.objects.all()
    n = len(obj)
    for i in obj:
        print(i.likes)
        if i.post == str(slug):
            if (i.user == request.user) and i.likes == True:
                for j in fuck:
                    if j.post == str(slug):
                        j.likes -= 1
                        j.save()
                        i.likes = False
                        i.save()
                        break
            elif (i.user == request.user) and i.likes == False:
                for j in fuck:
                    if j.post == str(slug):
                        j.likes += 1
                        j.save()
                        i.likes = True
                        i.save()
                        break
        elif i == obj[n-1] and i.post != str(slug):
            like = models.PostLikes()
            like.post = str(slug)
            like.likes = True
            like.user = request.user
            like.save()
            for j in fuck:
                if j.post == str(slug):
                    j.likes += 1
                    j.save()
    if len(obj) == 0:
        like = models.PostLikes()
        like.post = str(slug)
        like.likes = True
        like.user = request.user
        like.save()
        for j in fuck:
            if j.post == str(slug):
                j.likes += 1
                j.save()
    return redirect(request.META.get('HTTP_REFERER'))

student/templates/student/base.html
{% extends 'polling_station/base_template.html' %}

{% block side-nav %}
    <ul class="vertical-list">
        <h4>What do you wanna do?</h4>
        <li> <a href="#" class="dd-a"><b>Invite Friend</b></a> </li>
        <li> <a href="#" class="dd-a"><b>Share This Page</b></a> </li>
        <li> <a href="#" class="dd-a"><b>About Us</b></a> </li>
      </ul>
{% endblock %}

student/templates/student/enroll.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {%load static from staticfiles%}
      <link rel="stylesheet" href="{% static 'styles.css'%}">
    <title>Polling Station</title>
  </head>
  <body>
    <div class="wrapper">
        <h1>Enroll Into Our System</h1>
        <form action="{% url 'enroll' %}" method="POST" class="enroll-form" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
         <input type="submit" value="Next">
        </form>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

student/templates/student/enroll1.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {%load static from staticfiles%}
      <link rel="stylesheet" href="{% static 'styles.css'%}">
    <title>Polling Station</title>
  </head>
  <body>
    <div class="wrapper">
        <h1>Sign Up</h1>
        <h4>The Username is your Student Number</h4>
        <form action="{% url 'student:enroll1' %}" method="POST" class="enroll-form">
            {% csrf_token %}
            {{ user_form.as_p }}
            <br />
         <input type="submit" value="Enroll">
        </form>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

student/templates/student/enrolled.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {%load static from staticfiles%}
      <link rel="stylesheet" href="{% static 'styles.css'%}">
    <title>Polling Station</title>
  </head>
  <body>
    <div class="wrapper">
        <h2>Congratulations! You have succesfully enrolled into the system.</h2>
        <h3>Allow us take you to our Homepage</h3>
        <p>To do this follow the below link</p>
        <div>
            <a href="{% url 'student:login' %}" class="lonely-a">Take Me</a>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

student/templates/student/feedback.html
{% extends 'student/base.html' %}

{% block content %}
<h1>Feedback</h1>
    {% for comment in comments %}
        <div class="feed-back-content">
            <span>
                <img id="feedback-image" src="{{ details.photo.url }}" alt="">
            </span>
            <h3 style="text-align: left">{{ comment.user }}</h3>
            <p>{{ comment.comment }}</p>
            <span class="time-right">
                {{ comment.time }}
            </span>
        </div>
    {% endfor %}
{% endblock %}

student/templates/student/logout.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {%load static from staticfiles%}
      <link rel="stylesheet" href="{% static 'styles.css'%}">
    <title>Polling Station</title>
  </head>
  <body>
    <div class="wrapper">
        <h3>You have successfully been log out. <br />
        </h3>
        <p><b>We appreciate the time you have spent with us</b></p>
        <p>If you would love logging in again follow the link below</p>
        <div>

            <a href="{% url 'student:login' %}" class="lonely-a">Take Me</a>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

student/templates/student/posts.html
{% extends 'student/base.html' %}

{% block content %}
<script type="text/javascript">
    function openForm() {
    document.getElementById("popForm").style.display="block";
    }

    function closeForm() {

    document.getElementById("popForm").style.display="none";
    }
    function openInput() {
        document.getElementById("popInput").style.display="block";
    }
    function closeInput() {
        document.getElementById("popInput").style.display="none"
    }
    function openLikes(clickedId) {
        let i;
        let clickedComment = "";
        for (i=0; i<clickedId.length-2; i++ )
        {
            clickedComment += clickedId[i]
        }
        document.getElementById(clickedComment).style.display="none"
        document.getElementById(clickedId).style.display="block"
    }
    function openComments(clickedId) {
            var clickedLike = clickedId + "_1"
            document.getElementById(clickedLike).style.display="none"
            document.getElementById(clickedId).style.display="block"
    }
    function closeLikes(clickedId) {
        document.getElementById(clickedId).style.display="none"
    }
    function closeComments(clickedId) {
        document.getElementById(clickedId).style.display="none"
    }

</script>
<h1>Updates and NewsFeed on Election Status</h1>
<div>Create a post on this site:
<button type="button" class="open-button" onclick="openForm()">Create Post</button></div>
<div class="form-popup" id="popForm">
    <form action="{% url 'student:make_post' %}" class="form-container" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <h1>Create a Post</h1>
        <textarea name="post" id="post" cols="30" rows="10">Your post...</textarea>
        <hr />
        <div><b>Upload Image:</b>
        <button type="button" onclick="openInput()" class="open-button">Upload</button>
        </div>
        <div class="input-popup" id="popInput" style="display: none">
            <label for="post-image-upload">Your Image: <input type="file" id="post-image-upload" /> </label>
            <button type="button" onclick="closeInput()" class="cancel-btn"><b>Cancel Upload</b></button>
        </div>
        <input type="submit" class="post-btn" value="Post">
        <button type="button" class="cancel-btn" onclick="closeForm()">Close</button>
    </form>
</div>

{% if l_posts != 0 %}
{% for post in posts %}
    <div class="feed-back-content">
        <div>
            <img src="{{ post.userPhoto.url }}" id="profile" alt="profile" />
            <h3 style="text-align: left">{{ post.user }}</h3>
            <p>{{ post.post }}</p>
            <span class="time-right">
                {{ post.time }}
            </span>
            <div class="post-photo">
                <img src="{{ post.photo.url }}" style="width: 500px; height: auto; margin-top: 10%;" alt="profile" />
            </div>
            <span class="likes-comments">
                <button type="button" onclick="openLikes(this.name)" class="like-buttons" name={{ post.keyComment }}>Likes</button>({{ post.likes }})
                <a href="{% url 'student:like' slug=post.post %}" class="likes-a">Like</a>
                <button type="button" onclick="openComments(this.name)" class="like-buttons" name={{ post.key }}>
                    Comments</button>({{ post.comments }})
            </span>

        </div>
                <div class="comment-content" id={{ post.key }}>
                    <div>
                        <span>
                            <button onclick="closeComments(this.name)" style="float: left; background-color: red"
                                    name={{ post.key }} class="like-buttons">Hide Comments</button>
                        <p style="float: none; margin-top: 0; text-align: center; text-decoration: none">
                    <b><u>Comments On This Post:</u></b></p>
                    </span>
                    </div>
                    {% for comment in comments %}
                    {% if post.post == comment.post %}
                    <div class="comment-contents">
                        <img src="{{ comment.photo.url }}" alt="profile" />
                        <h3 style="text-align: left">{{ comment.user }}</h3>
                        <p>{{ comment.comment }}</p>
                        <span class="time-right">
                    {{ comment.time }}
                    </span>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>

        <div class="comment-content" id={{post.keyComment}}>
            <div>
                <span>
                    <button onclick="closeLikes(this.name)" style="float: left; background-color: red"
                            name={{post.keyComment}} class="like-buttons">Hide Likes</button>
                    <p style="float: none; margin-top: 0; text-align: center; text-decoration: none">
                    <b><u>Post Likes</u></b></p>
                </span>
            </div>
            {% for like in likes %}
            {% if post.post == like.post %}
                    <div class="comment-contents">
                        <img src="{{ like.photo.url }}" alt="profile" />
                        <h3 style="text-align: left">{{ like.user }}</h3>
                        <span class="time-right">
                        {{ like.time }}
                        </span>
                    </div>
            {% endif %}
            {% endfor %}
        </div>

        <div style="width: 38%; float: bottom">
            <form action="{% url 'student:post_comment' slug=post.post %}" method="POST" class="post-comment-form">
            {% csrf_token %}
            <span class="post-comment">
            <textarea name="comment" id="post-comment" cols="30" rows="1">Your comment...</textarea>
            <button type="submit" class="post-btn">Comment</button>
            </span>
            </form>
        </div>
    </div>
{% endfor %}
{% endif %}

{% endblock %}

student/templates/student/profile.html
{% extends 'student/base.html' %}

{% block content %}
<hr />
<h1>Student Profile</h1>
<hr />
    <div class="image-container">
        <img src="{{details.photo.url}}" alt="Profile">
        <div class="image-title">Your Profile Picture</div>
    </div>
<div>
    <p><b class="details-label">Student's full name:</b> <b class="details">{{details.full_name}}</b></p>
    <p><b class="details-label">Your College:</b> <b class="details">{{details.college}}</b></p>
    <p><b class="details-label">Your Department:</b> <b class="details">{{details.department}}</b></p>
    <p><b class="details-label">Your Program:</b> <b class="details">{{details.program}}</b></p>
    <p><b class="details-label">Year Of Study:</b> <b class="details">{{details.year_of_study}}</b></p>
    <p><b class="details-label">Your Registration Number:</b> <b class="details">{{details.reg_no}}</b></p>
    <p><b class="details-label">Your Student Number:</b> <b class="details">{{details.student_no}}</b></p>
    <p><b class="details-label">Your Birthday:</b> <b class="details">{{details.date_of_birth}}</b></p>
    <p><b class="details-label">Your Email Address:</b> <b class="details">{{details.email}}</b></p>
    <p><b class="details-label">Your Mobile Number:</b> <b class="details">{{details.mobile}}</b></p>
    <p><b class="details-label">Your Phone Number:</b> <b class="details">{{details.phone}}</b></p>
</div>
{% endblock %}