candidate/urls.py
from django.urls import path, re_path
from . import views

app_name = 'candidate'

urlpatterns = [
    re_path(r'^$', views.candidate_hp, name='homepage'),
    path('current-Cabinet/', views.currentCabinet, name='current-cabinet'),
    path('previous-Cabinet/', views.previousCabinet, name='previous-cabinet'),
    path('The-Current-Contestants/', views.contestants, name='current-contestants'),
]

polling_station/urls.py
from django.contrib import admin
from django.urls import path, include
from student import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

app_name = 'main'

urlpatterns = [
    path('votting/', include('votting.urls', namespace='votting')),
    path('candidate/', include('candidate.urls', namespace='candidate')),
    path('student/', include('student.urls', namespace='student')),
    path('', views.start_page, name='start'),
    path('homepage/', views.home_page, name='homepage'),
    path('student/login/', views.login_page, name='login'),
    path('student/enroll/', views.enroll_page, name='enroll'),
    path('admin/', admin.site.urls),
]

urlpatterns += staticfiles_urlpatterns()

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

student/urls.py
from django.urls import path, re_path
from . import views

app_name = 'student'

urlpatterns = [
    # re_path(r'^$', views.student_hp, name='homepage'),
    path('<str:slug>/login', views.login_page),
    path('login/', views.login_page, name='login'),
    path('start-enroll/', views.enroll_page, name='enroll'),
    path('profile/', views.profile, name='profile'),
    path('feedback/', views.feedback, name='feedback'),
    path('User-comment/', views.comment, name='comment'),
    path('posts/', views.posts, name='posts'),
    path('posts/let-me-create-a-post/', views.make_post, name='make_post'),
    path('posts/add-comment-to-current-post/<str:slug>', views.post_comment, name='post_comment'),
    path('posts/like-current-post/<str:slug>', views.like_post, name='like'),
    path('create-a-user-account/', views.create_user, name='enroll1'),
    path('enrolled-thanks/', views.enrolled, name='enrolled'),
    path('log-out-current-user/', views.logout_user, name='logout'),
    path('privacy-policies-and-agreement-terms/', views.privacy, name='privacy'),

]

candidate/models.py
from django.db import models

# Create your models here.

class PreviousCabinet(models.Model):
    colleges = [('CEDAT', 'College Of Engineering Design Art ANd Technology'),
                ('COBAMS', 'Economics')
                ]
    departments = []
    programs = []
    year = [('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')]
    sexes = [('m', 'Male'), ('f', 'female'), ('u', 'undefined')]

    college = models.CharField(max_length=100, choices=colleges, help_text='From the dropdown menu select your college')
    department = models.CharField(max_length=100, help_text='Choose your department')
    program = models.CharField(max_length=50, help_text='What is your Program')
    year_of_study = models.CharField(max_length=4, choices=year, help_text='Select your your of study')
    full_name = models.CharField(max_length=100, help_text='Enter Your full official name')
    reg_no = models.CharField(max_length=20, primary_key=True, help_text='Enter your Registration number')
    student_no = models.CharField(max_length=20, default='', help_text='Your student number')
    date_of_birth = models.DateField(blank=True, null=True, help_text='Enter your birthday')
    email = models.EmailField(default='', help_text='The email will only be used for official purposes')
    photo = models.ImageField(blank=True, default='default.jpg', help_text='This will be your profile picture')
    sex = models.CharField(max_length=10, choices=sexes, help_text='Sex', default='')
    post = models.CharField(max_length=100, help_text='post of leadership')
    year_of_service = models.CharField(max_length=20, help_text='academic year of operation')

    def __str__(self):
        return self.full_name

class Contestants(models.Model):
    colleges = [('CEDAT', 'College Of Engineering Design Art ANd Technology'),
                ('COBAMS', 'Economics')
                ]
    departments = []
    programs = []
    year = [('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')]
    sexes = [('m', 'Male'), ('f', 'female'), ('u', 'undefined')]

    college = models.CharField(max_length=100, choices=colleges, help_text='From the dropdown menu select your college')
    department = models.CharField(max_length=100, help_text='Choose your department')
    program = models.CharField(max_length=50, help_text='What is your Program')
    year_of_study = models.CharField(max_length=4, choices=year, help_text='Select your your of study')
    full_name = models.CharField(max_length=100, help_text='Enter Your full official name')
    reg_no = models.CharField(max_length=20, primary_key=True, help_text='Enter your Registration number')
    student_no = models.CharField(max_length=20, default='', help_text='Your student number')
    date_of_birth = models.DateField(blank=True, null=True, help_text='Enter your birthday')
    email = models.EmailField(default='', help_text='The email will only be used for official purposes')
    photo = models.ImageField(blank=True, default='default.jpg', help_text='This will be your profile picture')
    sex = models.CharField(max_length=10, choices=sexes, help_text='Sex', default='')
    post = models.CharField(max_length=100, help_text='post of leadership')
    nomination = models.IntegerField(help_text='Student Nomination', default=0)

    def __str__(self):
        return self.full_name

class CurrentCabinet(models.Model):
    colleges = [('CEDAT', 'College Of Engineering Design Art ANd Technology'),
                ('COBAMS', 'Economics')
                ]
    departments = []
    programs = []
    year = [('1', 'One'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five')]
    sexes = [('m', 'Male'), ('f', 'female'), ('u', 'undefined')]

    college = models.CharField(max_length=100, choices=colleges, help_text='From the dropdown menu select your college')
    department = models.CharField(max_length=100, help_text='Choose your department')
    program = models.CharField(max_length=50, help_text='What is your Program')
    year_of_study = models.CharField(max_length=4, choices=year, help_text='Select your your of study')
    full_name = models.CharField(max_length=100, help_text='Enter Your full official name')
    reg_no = models.CharField(max_length=20, primary_key=True, help_text='Enter your Registration number')
    student_no = models.CharField(max_length=20, default='', help_text='Your student number')
    date_of_birth = models.DateField(blank=True, null=True, help_text='Enter your birthday')
    email = models.EmailField(default='', help_text='The email will only be used for official purposes')
    photo = models.ImageField(blank=True, default='default.jpg', help_text='This will be your profile picture')
    sex = models.CharField(max_length=10, choices=sexes, help_text='Sex', default='')
    post = models.CharField(max_length=100, help_text='post of leadership')
    year_of_service = models.CharField(max_length=20, help_text='academic year of operation')

    def __str__(self):
        return self.full_name

candidate/views.py
from django.shortcuts import render
from . import models
from student.models import Profile

# Create your views here.

def candidate_hp(request):
    details = Profile.objects.get(student_no=request.user)
    return render(request, 'candidate/intro.html', {'details':details})

def contestants(request):
    obj = models.Contestants.objects.all()
    length = len(obj)
    details = Profile.objects.get(student_no=request.user)
    return render(request, 'candidate/contestants.html', {'details':details, 'contestants':obj, 'length':length})
def currentCabinet(request):
    obj = models.CurrentCabinet.objects.all()
    length = len(obj)
    details = Profile.objects.get(student_no=request.user)
    return render(request, 'candidate/current.html', {'details':details, 'currentCabinets':obj, 'length':length})
def previousCabinet(request):
    obj = models.PreviousCabinet.objects.all()
    length = len(obj)
    details = Profile.objects.get(student_no=request.user)
    return render(request, 'candidate/previous.html', {'details':details, 'previousCabinets':obj, 'length':length})

candidate/templates/candidate/base.html
{% extends 'polling_station/base_template.html' %}

{% block side-nav %}
    <ul class="vertical-list">
        <h4>What do you wanna do?</h4>
        <li> <a href="{% url 'candidate:current-cabinet' %}" class="dd-a"><b>Current leaders</b></a> </li>
        <li> <a href="{% url 'candidate:current-contestants' %}" class="dd-a"><b>contestants</b></a> </li>
        <li> <a href="{% url 'candidate:previous-cabinet' %}" class="dd-a"><b>History Of Leaders</b></a> </li>
      </ul>
{% endblock %}

candidate/templates/candidate/contestants.html
{% extends 'candidate/base.html' %}

{% block content %}
<h1>The Contestants</h1>
<hr />
{% if length == 0 %}

    <h2 style="color: red">
        <b>Hey dear! Currently we do not have entries in thsi section yet, but very soon we will</b>
    </h2>

{% else %}

<table class="contestant-image">
     <thead>
     <tr>
            <th colspan="7">Full Name</th>
            <th>Sex</th>
            <th>College</th>
            <th colspan="4">Department</th>
            <th>Program</th>
            <th>Year of study</th>
            <th>post</th>
            <th colspan="4">Contestant Image</th>
     </tr>
     </thead>
        <tbody>
        {% for contestant in contestants %}
        <tr>
            <td colspan="7">{{ contestant.full_name }}</td>
            <td>{{ contestant.sex }}</td>
            <td>{{ contestant.college }}</td>
            <td colspan="4">{{ contestant.department }}</td>
            <td>{{ contestant.program }}</td>
            <td>{{ contestant.year_of_study }}</td>
            <td>{{ contestant.post }}</td>
            <td colspan="4"><span> <img src="{{ contestant.photo.url }}" id="contestant-image"
                                             style="width: 100px" alt="Image"> </span></td>
        </tr>
        {% endfor %}
        </tbody>
</table>

{% endif %}

{% endblock %}

candidate/templates/candidate/current.html
{% extends 'candidate/base.html' %}

{% block content %}
<h1>The Current Cabinet</h1>
<hr />
{% if length == 0 %}

    <h2>
        <b style="color: red">Hey dear! Currently we do not have entries in thsi section yet, but very soon we will</b>
    </h2>

{% else %}

    <table class="contestant-image">
     <thead>
     <tr>
         <th colspan="5">Year Of Service</th>
         <th colspan="15">Year Of Service</th>
     </tr>
     <tr>
            <th colspan="7">Full Name</th>
            <th>Sex</th>
            <th>College</th>
            <th colspan="4">Department</th>
            <th>Program</th>
            <th>Year of study</th>
            <th>post</th>
            <th colspan="4">Image Of Official</th>
     </tr>
     </thead>
        <tbody>
        {% for currentCabinet in currentCabinets %}
        <tr>
            <td colspan="7">{{ currentCabinet.full_name }}</td>
            <td>{{ currentCabinet.sex }}</td>
            <td>{{ currentCabinet.college }}</td>
            <td colspan="4">{{ currentCabinet.department }}</td>
            <td>{{ currentCabinet.program }}</td>
            <td>{{ currentCabinet.year_of_study }}</td>
            <td>{{ currentCabinet.post }}</td>
            <td colspan="4"><span> <img src="{{ currentCabinet.photo.url }}" id="contestant-image"
                                             style="width: 100px" alt="Image"> </span></td>
        </tr>
        {% endfor %}
        </tbody>
</table>
{% endif %}

{% endblock %}

candidate/templates/candidate/intro.html
{% extends 'candidate/base.html' %}

{% block content %}
<h1>The Candidate Section</h1>
{% endblock %}

candidate/templates/candidate/previous.html
{% extends 'candidate/base.html' %}

{% block content %}
<h1>The Previous Cabinet</h1>
<hr />
{% if length == 0 %}

    <h2 style="color: red">
        <b>Hey dear! Currently we do not have entries in thsi section yet, but very soon we will</b>
    </h2>

{% else %}

    <table class="contestant-image">
     <thead>
     <tr>
         <th colspan="5">Year Of Service</th>
         <th colspan="15">Year Of Service</th>
     </tr>
     <tr>
            <th colspan="7">Full Name</th>
            <th>Sex</th>
            <th>College</th>
            <th colspan="4">Department</th>
            <th>Program</th>
            <th>Year of study</th>
            <th>post</th>
            <th colspan="4">Contestant Image</th>
     </tr>
     </thead>
        <tbody>
        {% for previousCabinet in previousCabinets %}
        <tr>
            <td colspan="7">{{ previousCabinet.full_name }}</td>
            <td>{{ previousCabinet.sex }}</td>
            <td>{{ previousCabinet.college }}</td>
            <td colspan="4">{{ previousCabinet.department }}</td>
            <td>{{ previousCabinet.program }}</td>
            <td>{{ previousCabinet.year_of_study }}</td>
            <td>{{ previousCabinet.post }}</td>
            <td colspan="4"><span> <img src="{{ previousCabinet.photo.url }}" id="contestant-image"
                                             style="width: 100px" alt="Image"> </span></td>
        </tr>
        {% endfor %}
        </tbody>
</table>

{% endif %}

{% endblock %}